version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eta-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sailesh
      POSTGRES_DB: eta_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eta_user -d eta_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - eta-tracker-network

networks:
  eta-tracker-network:
    driver: bridge

volumes:
  postgres_data:
